server:
  port: 8082
spring:
  application:
    name: fraud
  datasource:
    password: password
    url: jdbc:postgresql://localhost:2345/fraud
    username: amigoscode
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true